
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.reward
{
public sealed partial class ConfReward : Luban.BeanBase
{
    public ConfReward(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.Dictionary<int, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Rewards.Add(_k0, _v0);}}
    }

    public static ConfReward DeserializeConfReward(ByteBuf _buf)
    {
        return new reward.ConfReward(_buf);
    }

    /// <summary>
    /// 奖励id
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.Dictionary<int, int> Rewards;
   
    public const int __ID__ = -1104894030;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

