
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.reward
{
public partial class TbReward
{
    private readonly System.Collections.Generic.Dictionary<int, reward.ConfReward> _dataMap;
    private readonly System.Collections.Generic.List<reward.ConfReward> _dataList;
    
    public TbReward(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, reward.ConfReward>(n);
        _dataList = new System.Collections.Generic.List<reward.ConfReward>(n);
        for(int i = n ; i > 0 ; --i)
        {
            reward.ConfReward _v;
            _v = global::GameConfig.reward.ConfReward.DeserializeConfReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, reward.ConfReward> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<reward.ConfReward> DataList => _dataList;

    public reward.ConfReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public reward.ConfReward Get(int key) => _dataMap[key];
    public reward.ConfReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

