using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using GameConfig;
using UnityEngine;

namespace Builder
{
    /// <summary>
    /// 每次导表后自动生成 LanguageKey 常量类。
    /// 目标位置：Assets/GameScripts/HotFix/GameLogic/Localization/LanguageKey.cs
    /// </summary>
    public static class LanguageGenerateKeyEditor
    {
        private const string OutputDir = "Assets/GameScripts/HotFix/GameLogic/Localization";
        private const string FileName = "LanguageKey.cs";
        private const string NamespaceName = "GameLogic.Localization";

        public static void Generate()
        {
            // 1. 加载编辑器模式下的配置表
            try
            {
                ConfigSystem.Instance.LoadEditor();
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[LanguageKey生成] 加载配置表失败: {e.Message}");
                return;
            }

            // 2. 获取 TbLanguageContent 中的所有 key
            var langContentTable = ConfigSystem.Instance.Tables?.TbLanguageContent;
            if (langContentTable == null || langContentTable.DataList == null || langContentTable.DataList.Count == 0)
            {
                Debug.LogWarning("[LanguageKey生成] TbLanguageContent 为空，跳过生成");
                return;
            }

            var keys = new List<string>();
            foreach (var item in langContentTable.DataList)
            {
                if (!string.IsNullOrEmpty(item.Id))
                    keys.Add(item.Id);
            }

            if (keys.Count == 0)
            {
                Debug.LogWarning("[LanguageKey生成] 没有可用的多语言 Key，跳过生成");
                return;
            }

            // 3. 生成代码（使用 const string 而非 enum，因为 Key 是字符串且可能包含非法标识符字符）
            var sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此文件由 LanguageGenerateKeyEditor 自动生成，每次导表后更新。");
            sb.AppendLine("//     请勿手动修改此文件！");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine($"namespace {NamespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 多语言 Key 常量类（共 {keys.Count} 个 Key）。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class LanguageKey");
            sb.AppendLine("    {");

            // 用于检测重复的 sanitized 名称
            var usedNames = new HashSet<string>();

            foreach (string key in keys)
            {
                string fieldName = SanitizeIdentifier(key, usedNames);
                sb.AppendLine($"        public const string {fieldName} = \"{EscapeString(key)}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 4. 写入文件
            string outputPath = Path.Combine(Application.dataPath.Replace("Assets", ""), OutputDir);
            if (!Directory.Exists(outputPath))
                Directory.CreateDirectory(outputPath);

            string filePath = Path.Combine(outputPath, FileName);
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);

            Debug.Log($"[LanguageKey生成] 已生成 {FileName}，共 {keys.Count} 个 Key → {filePath}");

            // 5. 刷新 AssetDatabase，让 Unity 识别新文件
            UnityEditor.AssetDatabase.Refresh();
        }

        /// <summary>
        /// 将原始 Key 转为合法的 C# 标识符，处理重名。
        /// </summary>
        private static string SanitizeIdentifier(string rawKey, HashSet<string> usedNames)
        {
            if (string.IsNullOrEmpty(rawKey))
                return "_Empty";

            var sb = new StringBuilder(rawKey.Length);

            // 首字符不能是数字
            if (char.IsDigit(rawKey[0]))
                sb.Append('_');

            foreach (char c in rawKey)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string name = sb.ToString();

            // 处理重名：追加序号
            string candidate = name;
            int counter = 1;
            while (usedNames.Contains(candidate))
            {
                candidate = $"{name}_{counter}";
                counter++;
            }

            usedNames.Add(candidate);
            return candidate;
        }

        /// <summary>
        /// 转义字符串中的特殊字符（主要是双引号和反斜杠）。
        /// </summary>
        private static string EscapeString(string raw)
        {
            return raw.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
