
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class ConfLevel : Luban.BeanBase
{
    public ConfLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelName = _buf.ReadString();
        RewardId = _buf.ReadInt();
    }

    public static ConfLevel DeserializeConfLevel(ByteBuf _buf)
    {
        return new level.ConfLevel(_buf);
    }

    /// <summary>
    /// 语言id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string LevelName;
    /// <summary>
    /// 关卡奖励id
    /// </summary>
    public readonly int RewardId;
   
    public const int __ID__ = -98546506;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelName:" + LevelName + ","
        + "rewardId:" + RewardId + ","
        + "}";
    }
}

}

