
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public partial class TbLevel
{
    private readonly System.Collections.Generic.Dictionary<int, level.ConfLevel> _dataMap;
    private readonly System.Collections.Generic.List<level.ConfLevel> _dataList;
    
    public TbLevel(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.ConfLevel>();
        _dataList = new System.Collections.Generic.List<level.ConfLevel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            level.ConfLevel _v;
            _v = level.ConfLevel.DeserializeConfLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.ConfLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<level.ConfLevel> DataList => _dataList;

    public level.ConfLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.ConfLevel Get(int key) => _dataMap[key];
    public level.ConfLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

