//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 LanguageGenerateKeyEditor 自动生成，每次导表后更新。
//     请勿手动修改此文件！
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLogic.Localization
{
    /// <summary>
    /// 多语言 Key 常量类（共 7 个 Key）。
    /// </summary>
    public static class LanguageKey
    {
        public const string select_language_ch = "select_language_ch";
        public const string select_language_en = "select_language_en";
        public const string back_btn = "back_btn";
        public const string submit_btn = "submit_btn";
        public const string start_game_btn = "start_game_btn";
        public const string next_level_btn = "next_level_btn";
        public const string level_title = "level_title";
    }
}
