
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum LanguageCode
    {
        /// <summary>
        /// 中文
        /// </summary>
        Ch = 1,
        /// <summary>
        /// 英文
        /// </summary>
        En = 2,
    }

} 

