
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Cysharp.Threading.Tasks;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    public async UniTask TbItemAsync() 
    {
        if (m_TbItem != null)
        {
            return;
        }
        m_TbItem = new item.TbItem(await defaultLoaderAsync("item_tbitem"));
        m_TbItem.ResolveRef(this);
    }
    private language.TbLanguage m_TbLanguage;
    public language.TbLanguage TbLanguage 
    {
        get
        {
            if (m_TbLanguage == null)
            {
                m_TbLanguage = new language.TbLanguage(defaultLoader("language_tblanguage"));
                m_TbLanguage.ResolveRef(this);
            }
            return m_TbLanguage;
        }
        set
        {
            m_TbLanguage = value;
            m_TbLanguage.ResolveRef(this);
        }
    }
    public async UniTask TbLanguageAsync() 
    {
        if (m_TbLanguage != null)
        {
            return;
        }
        m_TbLanguage = new language.TbLanguage(await defaultLoaderAsync("language_tblanguage"));
        m_TbLanguage.ResolveRef(this);
    }
    private language.TbLanguageContent m_TbLanguageContent;
    public language.TbLanguageContent TbLanguageContent 
    {
        get
        {
            if (m_TbLanguageContent == null)
            {
                m_TbLanguageContent = new language.TbLanguageContent(defaultLoader("language_tblanguagecontent"));
                m_TbLanguageContent.ResolveRef(this);
            }
            return m_TbLanguageContent;
        }
        set
        {
            m_TbLanguageContent = value;
            m_TbLanguageContent.ResolveRef(this);
        }
    }
    public async UniTask TbLanguageContentAsync() 
    {
        if (m_TbLanguageContent != null)
        {
            return;
        }
        m_TbLanguageContent = new language.TbLanguageContent(await defaultLoaderAsync("language_tblanguagecontent"));
        m_TbLanguageContent.ResolveRef(this);
    }
    private level.TbLevel m_TbLevel;
    public level.TbLevel TbLevel 
    {
        get
        {
            if (m_TbLevel == null)
            {
                m_TbLevel = new level.TbLevel(defaultLoader("level_tblevel"));
                m_TbLevel.ResolveRef(this);
            }
            return m_TbLevel;
        }
        set
        {
            m_TbLevel = value;
            m_TbLevel.ResolveRef(this);
        }
    }
    public async UniTask TbLevelAsync() 
    {
        if (m_TbLevel != null)
        {
            return;
        }
        m_TbLevel = new level.TbLevel(await defaultLoaderAsync("level_tblevel"));
        m_TbLevel.ResolveRef(this);
    }
    private reward.TbReward m_TbReward;
    public reward.TbReward TbReward 
    {
        get
        {
            if (m_TbReward == null)
            {
                m_TbReward = new reward.TbReward(defaultLoader("reward_tbreward"));
                m_TbReward.ResolveRef(this);
            }
            return m_TbReward;
        }
        set
        {
            m_TbReward = value;
            m_TbReward.ResolveRef(this);
        }
    }
    public async UniTask TbRewardAsync() 
    {
        if (m_TbReward != null)
        {
            return;
        }
        m_TbReward = new reward.TbReward(await defaultLoaderAsync("reward_tbreward"));
        m_TbReward.ResolveRef(this);
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;
    
    public Tables(System.Func<string, ByteBuf> loader, System.Func<string, UniTask<ByteBuf>> loaderAsync)
    {
        SetDefaultLoader(loader);
        SetDefaultLoaderAsync(loaderAsync);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }
    
    System.Func<string, UniTask<ByteBuf>> defaultLoaderAsync;
    
    public void SetDefaultLoaderAsync(System.Func<string, UniTask<ByteBuf>> loaderAsync)
    {
        defaultLoaderAsync = null;
        defaultLoaderAsync = loaderAsync;
    }
    //public partial void Init();
    
    public void Init()
    {
    }
}

}
