
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    private language.TbLanguage m_TbLanguage;
    public language.TbLanguage TbLanguage 
    {
        get
        {
            if (m_TbLanguage == null)
            {
                m_TbLanguage = new language.TbLanguage(defaultLoader("language_tblanguage"));
                m_TbLanguage.ResolveRef(this);
            }
            return m_TbLanguage;
        }
        set
        {
            m_TbLanguage = value;
            m_TbLanguage.ResolveRef(this);
        }
    }
    private language.TbLanguageContent m_TbLanguageContent;
    public language.TbLanguageContent TbLanguageContent 
    {
        get
        {
            if (m_TbLanguageContent == null)
            {
                m_TbLanguageContent = new language.TbLanguageContent(defaultLoader("language_tblanguagecontent"));
                m_TbLanguageContent.ResolveRef(this);
            }
            return m_TbLanguageContent;
        }
        set
        {
            m_TbLanguageContent = value;
            m_TbLanguageContent.ResolveRef(this);
        }
    }
    private level.TbLevel m_TbLevel;
    public level.TbLevel TbLevel 
    {
        get
        {
            if (m_TbLevel == null)
            {
                m_TbLevel = new level.TbLevel(defaultLoader("level_tblevel"));
                m_TbLevel.ResolveRef(this);
            }
            return m_TbLevel;
        }
        set
        {
            m_TbLevel = value;
            m_TbLevel.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
