
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.language
{
public sealed partial class ConfLanguageContent : Luban.BeanBase
{
    public ConfLanguageContent(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Value = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Value[__index0] = __e0;}}
    }

    public static ConfLanguageContent DeserializeConfLanguageContent(ByteBuf _buf)
    {
        return new language.ConfLanguageContent(_buf);
    }

    /// <summary>
    /// 多语言key
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string[] Value;
   
    public const int __ID__ = -1778096505;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Luban.StringUtil.CollectionToString(Value) + ","
        + "}";
    }
}

}

