
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.language
{
public sealed partial class ConfLanguage : Luban.BeanBase
{
    public ConfLanguage(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        LanguageCode = (LanguageCode)_buf.ReadInt();
        Font = _buf.ReadString();
        BaseLine = _buf.ReadFloat();
    }

    public static ConfLanguage DeserializeConfLanguage(ByteBuf _buf)
    {
        return new language.ConfLanguage(_buf);
    }

    /// <summary>
    /// 语言id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 语言选择key
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 语言类型
    /// </summary>
    public readonly LanguageCode LanguageCode;
    /// <summary>
    /// 字体
    /// </summary>
    public readonly string Font;
    /// <summary>
    /// 字体纵向偏移
    /// </summary>
    public readonly float BaseLine;
   
    public const int __ID__ = 1092902290;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "languageCode:" + LanguageCode + ","
        + "font:" + Font + ","
        + "baseLine:" + BaseLine + ","
        + "}";
    }
}

}

