
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.language
{
public partial class TbLanguageContent
{
    private readonly System.Collections.Generic.Dictionary<string, language.ConfLanguageContent> _dataMap;
    private readonly System.Collections.Generic.List<language.ConfLanguageContent> _dataList;
    
    public TbLanguageContent(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, language.ConfLanguageContent>();
        _dataList = new System.Collections.Generic.List<language.ConfLanguageContent>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            language.ConfLanguageContent _v;
            _v = language.ConfLanguageContent.DeserializeConfLanguageContent(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, language.ConfLanguageContent> DataMap => _dataMap;
    public System.Collections.Generic.List<language.ConfLanguageContent> DataList => _dataList;

    public language.ConfLanguageContent GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public language.ConfLanguageContent Get(string key) => _dataMap[key];
    public language.ConfLanguageContent this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

