
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.language
{
public partial class TbLanguage
{
    private readonly System.Collections.Generic.Dictionary<int, language.ConfLanguage> _dataMap;
    private readonly System.Collections.Generic.List<language.ConfLanguage> _dataList;
    
    public TbLanguage(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, language.ConfLanguage>();
        _dataList = new System.Collections.Generic.List<language.ConfLanguage>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            language.ConfLanguage _v;
            _v = language.ConfLanguage.DeserializeConfLanguage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, language.ConfLanguage> DataMap => _dataMap;
    public System.Collections.Generic.List<language.ConfLanguage> DataList => _dataList;

    public language.ConfLanguage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public language.ConfLanguage Get(int key) => _dataMap[key];
    public language.ConfLanguage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

